de_capstone:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: de-zoomcamp-485107
      dataset: dbt_iso_ne
      threads: 4
      keyfile: /workspaces/de-capstone/my-creds/de-zoomcamp-485107-3cbafa3d7c94.json