gridpulse_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: de-zoomcamp-485107
      dataset: dbt_iso_ne
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"